p7zr to 7zd

diff --git a/v0 b/v0
--- a/v0
+++ b/v0
@@ -31,15 +31,15 @@ _7zd_which(){
             exe=7zd.${osname}.${arch}  
         ;;
         *)
-            p7zr_log error "Unsupported [arch=$arch] [os=$osname]!" >&2; 
+            p7zd_log error "Unsupported [arch=$arch] [os=$osname]!" >&2; 
             return 1 
         ;;
     esac
-    p7zr_log debug "Downloading: p7zip/main/bin/$exe"
+    p7zd_log debug "Downloading: p7zip/main/bin/$exe"
     if CACHE="$target/$exe" ___x_cmd_curl_gitx static-build "p7zip" main "bin/$exe" "$target/$exe"; then
         chmod +x "$target/$exe" && printf "%s" "$target/$exe"
     else
-        p7zr_log error "Fail to download: p7zip/main/bin/$exe"
+        p7zd_log error "Fail to download: p7zip/main/bin/$exe"
         return 1
     fi
 }
